django_logbox/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_logbox/admin.py,sha256=lZOcdC62TgodKpwHEUBX2cbxwxrThZqr81HF84TQAOw,2933
django_logbox/app_settings.py,sha256=jtAEM1LMYuA1Fg73GZq90IqzvsAtT3vfKz43nqJPlVY,1445
django_logbox/apps.py,sha256=dOwy4hUMHHQ_0W27Hphf98vbRr0GIUvfPRoKpYjHBHs,687
django_logbox/locale/ko_KR/LC_MESSAGES/django.mo,sha256=HCv5r8-ADpPfnCG-mPt6ywujEcre0q9MEIgq11zW1AU,3110
django_logbox/locale/ko_KR/LC_MESSAGES/django.po,sha256=p58HshARMcRWY_3mGW4eb_unyJAgremhLbcqBxusDtc,4252
django_logbox/middlewares.py,sha256=aAWDcAwbhP-tZbn2ypUO3c34hL8e46ttpYS0sUu07Qo,2698
django_logbox/migrations/0001_initial.py,sha256=6VT2pvAYWeTYYkxWm9XFi30U8cE-xJGADTvwQucEgqg,1999
django_logbox/migrations/0002_remove_serverlog_duration.py,sha256=1Xz2hUND59e31opN7LqflRS8Jm3JFZOKP4VJvxBEWnE,327
django_logbox/migrations/0003_rename_exception_serverlog_exception_type_and_more.py,sha256=LHYtGqdFWGwdgXMMKYJKtwcfMe23DI8pkAkK3_lc7JM,592
django_logbox/migrations/0004_alter_serverlog_client_ip_and_more.py,sha256=YmJjhVqFmQHBAQaKtJTH3ysIe7LjXRJ-oMNnfvIFpck,4123
django_logbox/migrations/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_logbox/models.py,sha256=vtZT-vFen2HIkGnJUZDXtqhItZaPEV0CKE43wzr0q_k,2555
django_logbox/threading.py,sha256=WpMn7LnE9W4CYvvwYc6PxOv82hDXqfXkL0uxeN0GBQg,2062
django_logbox/utils.py,sha256=nqxhuB6-PrhDu-jhHy6F6fSlmo1ozUyQ1_ywJaziLxM,2541
django_logbox-0.0.12.dist-info/METADATA,sha256=PNdczptaFm_iS2VN-wJZtstedIL81z6C2teZoud76FA,3197
django_logbox-0.0.12.dist-info/WHEEL,sha256=XbeZDeTWKc1w7CSIyre5aMDU_-PohRwTQceYnisIYYY,88
django_logbox-0.0.12.dist-info/RECORD,,
